# Generated by Django 6.0.2 on 2026-03-03 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villa', '0002_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('assigned_villa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='villa.villa')),
            ],
        ),
    ]
