# Generated by Django 6.0.2 on 2026-03-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villa', '0004_incident'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villa',
            name='is_available',
        ),
        migrations.AddField(
            model_name='villa',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='villas/'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='villa',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
