# Generated by Django 6.0.2 on 2026-03-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villa', '0005_remove_villa_is_available_villa_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
