# Generated by Django 6.0.2 on 2026-04-13 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villa', '0008_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='villa.staff'),
        ),
    ]
