# Generated by Django 6.0.2 on 2026-04-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villa', '0009_incident_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='amenities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='villa',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
