# Generated by Django 6.0.2 on 2026-04-29 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villa', '0010_villa_amenities_villa_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='VillaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='villa_gallery/')),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='villa.villa')),
            ],
        ),
    ]
